### ISSUE TITLE
Still active ?

### ISSUE THREAD

**Issue by StefH** [alexvictoor/mock4net#23]
Hello @alexvictoor ,

I found your project because I'm currently using the original Java version **WireMock**. However it seems that you are not very active.

Is it possible that I can help you on this project ? Maybe add me as an committer/author to this GitHub project ?

**Comment by alexvictoor** [comment]
Well, I am still alive :)
Glad you are interested by the project!
I have not lost interest on the project, days are just too short...
Since you ask, there are features inspired from wiremock I would be very happy to see in mock4net:
- scenarios, including stateful senarios
- admin rest api

Let me know if you are interested to implement one of those features. Also I am interested to know if you had something else in mind.

**Comment by StefH** [comment]
Hi Alex. Thanks for your nice project !

For this moment, I've forked your project and actually copied the code to a new project.

Things I want to implement are (not in particular order):

- Merge some PR's 
- Change project to .dotnet (currently only support for 4.5 is possible, maybe in future also netstandard1.3)
- Add RegEx and Func<string> matching
- Add some plural matching methods like `WithUrls(string[] urls)`
- Add Handlebar support
- Add Xml(2)Path matching
- Add JsonPath matching
- Add some `WithStatusCodeRange(200)` methods
- Add BasicAuth matching
- Add Cookie matching
- .... ?

Indeed and also:

- admin rest api (for that I want to add a new project ***.Server or something)
- scenarios, including stateful scenarios

**Comment by StefH** [comment]
Hello Alex.

I decided to create a new project based on this one. See https://github.com/StefH/WireMock.Net 

Currently I'm working on the admin interface, the first call is implemented, the others will follows later. Probably some refactoring is needed.
